application: tonystuff-1470519013212
version: beta1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css|pdf))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|pdf))

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest